<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UpdatePaymentTransactionRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true; // Authorization logic if needed
    }

    public function rules()
    {
        return [
            'payment_master_id' => ['sometimes', 'string', 'max:255', 'exists:payment_masters,id'],
            'payment_child_id' => ['nullable', 'string', 'max:255', 'exists:payment_children,id'],
            'transaction_id' => ['sometimes', 'string', 'max:255'],
            'reference_id' => ['nullable', 'string', 'max:255'],
            'type' => ['sometimes', 'string', 'max:255'],
            'payment_method' => ['sometimes', 'string', 'max:255'],
            'payment_gateway' => ['sometimes', 'string', 'max:255'],
            'gateway_response' => ['nullable', 'json'],
            'payment_method_details' => ['nullable', 'json'],
            'amount' => ['sometimes', 'numeric', 'regex:/^\d+(\.\d{1,2})?$/'],
            'fee' => ['sometimes', 'numeric', 'regex:/^\d+(\.\d{1,2})?$/'],
            'tax' => ['sometimes', 'numeric', 'regex:/^\d+(\.\d{1,2})?$/'],
            'net_amount' => ['nullable', 'numeric', 'regex:/^\d+(\.\d{1,2})?$/'],
            'currency' => ['sometimes', 'string', 'max:255'],
            'exchange_rate' => ['sometimes', 'numeric', 'regex:/^\d+(\.\d{1,2})?$/'],
            'status' => ['sometimes', 'string', 'max:255'],
            'card_last4' => ['nullable', 'string', 'max:255'],
            'card_brand' => ['nullable', 'string', 'max:255'],
            'card_country' => ['nullable', 'string', 'max:255'],
            'card_exp_month' => ['nullable', 'integer', 'max:11'],
            'card_exp_year' => ['nullable', 'integer', 'max:11'],
            'bank_name' => ['nullable', 'string', 'max:255'],
            'bank_account_last4' => ['nullable', 'string', 'max:255'],
            'bank_routing_number' => ['nullable', 'string', 'max:255'],
            'wallet_type' => ['nullable', 'string', 'max:255'],
            'wallet_number' => ['nullable', 'string', 'max:255'],
            'wallet_transaction_id' => ['nullable', 'string', 'max:255'],
            'installment_number' => ['nullable', 'integer', 'max:11'],
            'total_installments' => ['nullable', 'integer', 'max:11'],
            'initiated_at' => ['sometimes', 'date'],
            'authorized_at' => ['nullable', 'date'],
            'captured_at' => ['nullable', 'date'],
            'completed_at' => ['nullable', 'date'],
            'failed_at' => ['nullable', 'date'],
            'refunded_at' => ['nullable', 'date'],
            'fraud_indicators' => ['nullable', 'json'],
            'risk_score' => ['nullable', 'numeric', 'regex:/^\d+(\.\d{1,2})?$/'],
            'requires_review' => ['sometimes', 'boolean', 'max:1'],
            'metadata' => ['nullable', 'json'],
            'custom_fields' => ['nullable', 'json'],
            'notes' => ['nullable', 'string', 'max:65535'],
            'failure_reason' => ['nullable', 'string', 'max:65535'],
            'ip_address' => ['nullable', 'string', 'max:255', 'sometimes', 'ip'],
            'user_agent' => ['nullable', 'string', 'max:65535'],
            'location_data' => ['nullable', 'json'],
        ];
    }

    public function messages()
    {
        return [
            'payment_master_id.string' => 'The payment master id must be a string.',
            'payment_master_id.max' => 'The payment master id must not exceed 255 characters.',
            'payment_master_id.exists' => 'The selected payment master id is invalid or does not exist in payment masters.',
            'payment_child_id.string' => 'The payment child id must be a string.',
            'payment_child_id.max' => 'The payment child id must not exceed 255 characters.',
            'payment_child_id.exists' => 'The selected payment child id is invalid or does not exist in payment children.',
            'transaction_id.string' => 'The transaction id must be a string.',
            'transaction_id.max' => 'The transaction id must not exceed 255 characters.',
            'reference_id.string' => 'The reference id must be a string.',
            'reference_id.max' => 'The reference id must not exceed 255 characters.',
            'type.string' => 'The type must be a string.',
            'type.max' => 'The type must not exceed 255 characters.',
            'payment_method.string' => 'The payment method must be a string.',
            'payment_method.max' => 'The payment method must not exceed 255 characters.',
            'payment_gateway.string' => 'The payment gateway must be a string.',
            'payment_gateway.max' => 'The payment gateway must not exceed 255 characters.',
            'gateway_response.json' => 'The gateway response must be a valid JSON string.',
            'payment_method_details.json' => 'The payment method details must be a valid JSON string.',
            'amount.numeric' => 'The amount must be a number.',
            'amount.regex' => 'The amount must be a valid decimal number.',
            'fee.numeric' => 'The fee must be a number.',
            'fee.regex' => 'The fee must be a valid decimal number.',
            'tax.numeric' => 'The tax must be a number.',
            'tax.regex' => 'The tax must be a valid decimal number.',
            'net_amount.numeric' => 'The net amount must be a number.',
            'net_amount.regex' => 'The net amount must be a valid decimal number.',
            'currency.string' => 'The currency must be a string.',
            'currency.max' => 'The currency must not exceed 255 characters.',
            'exchange_rate.numeric' => 'The exchange rate must be a number.',
            'exchange_rate.regex' => 'The exchange rate must be a valid decimal number.',
            'status.string' => 'The status must be a string.',
            'status.max' => 'The status must not exceed 255 characters.',
            'card_last4.string' => 'The card last4 must be a string.',
            'card_last4.max' => 'The card last4 must not exceed 255 characters.',
            'card_brand.string' => 'The card brand must be a string.',
            'card_brand.max' => 'The card brand must not exceed 255 characters.',
            'card_country.string' => 'The card country must be a string.',
            'card_country.max' => 'The card country must not exceed 255 characters.',
            'card_exp_month.integer' => 'The card exp month must be an integer.',
            'card_exp_month.max' => 'The card exp month must not exceed 11 characters.',
            'card_exp_year.integer' => 'The card exp year must be an integer.',
            'card_exp_year.max' => 'The card exp year must not exceed 11 characters.',
            'bank_name.string' => 'The bank name must be a string.',
            'bank_name.max' => 'The bank name must not exceed 255 characters.',
            'bank_account_last4.string' => 'The bank account last4 must be a string.',
            'bank_account_last4.max' => 'The bank account last4 must not exceed 255 characters.',
            'bank_routing_number.string' => 'The bank routing number must be a string.',
            'bank_routing_number.max' => 'The bank routing number must not exceed 255 characters.',
            'wallet_type.string' => 'The wallet type must be a string.',
            'wallet_type.max' => 'The wallet type must not exceed 255 characters.',
            'wallet_number.string' => 'The wallet number must be a string.',
            'wallet_number.max' => 'The wallet number must not exceed 255 characters.',
            'wallet_transaction_id.string' => 'The wallet transaction id must be a string.',
            'wallet_transaction_id.max' => 'The wallet transaction id must not exceed 255 characters.',
            'installment_number.integer' => 'The installment number must be an integer.',
            'installment_number.max' => 'The installment number must not exceed 11 characters.',
            'total_installments.integer' => 'The total installments must be an integer.',
            'total_installments.max' => 'The total installments must not exceed 11 characters.',
            'initiated_at.date' => 'The initiated at must be a valid date and time.',
            'authorized_at.date' => 'The authorized at must be a valid date and time.',
            'captured_at.date' => 'The captured at must be a valid date and time.',
            'completed_at.date' => 'The completed at must be a valid date and time.',
            'failed_at.date' => 'The failed at must be a valid date and time.',
            'refunded_at.date' => 'The refunded at must be a valid date and time.',
            'fraud_indicators.json' => 'The fraud indicators must be a valid JSON string.',
            'risk_score.numeric' => 'The risk score must be a number.',
            'risk_score.regex' => 'The risk score must be a valid decimal number.',
            'requires_review.boolean' => 'The requires review must be true or false.',
            'requires_review.max' => 'The requires review must not exceed 1 characters.',
            'metadata.json' => 'The metadata must be a valid JSON string.',
            'custom_fields.json' => 'The custom fields must be a valid JSON string.',
            'notes.string' => 'The notes must be a string.',
            'notes.max' => 'The notes must not exceed 65535 characters.',
            'failure_reason.string' => 'The failure reason must be a string.',
            'failure_reason.max' => 'The failure reason must not exceed 65535 characters.',
            'ip_address.string' => 'The ip address must be a string.',
            'ip_address.max' => 'The ip address must not exceed 255 characters.',
            'user_agent.string' => 'The user agent must be a string.',
            'user_agent.max' => 'The user agent must not exceed 65535 characters.',
            'location_data.json' => 'The location data must be a valid JSON string.',
            'updated_by.string' => 'The updated by must be a string.',
            'updated_by.max' => 'The updated by must not exceed 255 characters.',
            'updated_at.date' => 'The updated at must be a valid date and time.',
        ];
    }
}
